//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APCollectionWeb.TgS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TgS.HSRPAuthorizationServiceSoap")]
    public interface HSRPAuthorizationServiceSoap {
        
        // CODEGEN: Generating message contract since element name fromdate from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHSRPAuthorizationDetails", ReplyAction="*")]
        APCollectionWeb.TgS.GetHSRPAuthorizationDetailsResponse GetHSRPAuthorizationDetails(APCollectionWeb.TgS.GetHSRPAuthorizationDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHSRPAuthorizationno", ReplyAction="*")]
        APCollectionWeb.TgS.GetHSRPAuthorizationnoResponse GetHSRPAuthorizationno(APCollectionWeb.TgS.GetHSRPAuthorizationnoRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPCharges", ReplyAction="*")]
        APCollectionWeb.TgS.UpdateHSRPChargesResponse UpdateHSRPCharges(APCollectionWeb.TgS.UpdateHSRPChargesRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPLaserCodes", ReplyAction="*")]
        APCollectionWeb.TgS.UpdateHSRPLaserCodesResponse UpdateHSRPLaserCodes(APCollectionWeb.TgS.UpdateHSRPLaserCodesRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPAffixation", ReplyAction="*")]
        APCollectionWeb.TgS.UpdateHSRPAffixationResponse UpdateHSRPAffixation(APCollectionWeb.TgS.UpdateHSRPAffixationRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPAvailableAtOffice", ReplyAction="*")]
        APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeResponse UpdateHSRPAvailableAtOffice(APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRegnOnAuthorizationDate", ReplyAction="*")]
        APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateResponse UpdateRegnOnAuthorizationDate(APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateRequest request);
        
        // CODEGEN: Generating message contract since element name fromdate from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAuthorizationnotRegistered", ReplyAction="*")]
        APCollectionWeb.TgS.GetAuthorizationnotRegisteredResponse GetAuthorizationnotRegistered(APCollectionWeb.TgS.GetAuthorizationnotRegisteredRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationDetails", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.GetHSRPAuthorizationDetailsRequestBody Body;
        
        public GetHSRPAuthorizationDetailsRequest() {
        }
        
        public GetHSRPAuthorizationDetailsRequest(APCollectionWeb.TgS.GetHSRPAuthorizationDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string todate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string officecode;
        
        public GetHSRPAuthorizationDetailsRequestBody() {
        }
        
        public GetHSRPAuthorizationDetailsRequestBody(string fromdate, string todate, string officecode) {
            this.fromdate = fromdate;
            this.todate = todate;
            this.officecode = officecode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.GetHSRPAuthorizationDetailsResponseBody Body;
        
        public GetHSRPAuthorizationDetailsResponse() {
        }
        
        public GetHSRPAuthorizationDetailsResponse(APCollectionWeb.TgS.GetHSRPAuthorizationDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHSRPAuthorizationDetailsResult;
        
        public GetHSRPAuthorizationDetailsResponseBody() {
        }
        
        public GetHSRPAuthorizationDetailsResponseBody(string GetHSRPAuthorizationDetailsResult) {
            this.GetHSRPAuthorizationDetailsResult = GetHSRPAuthorizationDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationno", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.GetHSRPAuthorizationnoRequestBody Body;
        
        public GetHSRPAuthorizationnoRequest() {
        }
        
        public GetHSRPAuthorizationnoRequest(APCollectionWeb.TgS.GetHSRPAuthorizationnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        public GetHSRPAuthorizationnoRequestBody() {
        }
        
        public GetHSRPAuthorizationnoRequestBody(string Authno) {
            this.Authno = Authno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationnoResponse", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.GetHSRPAuthorizationnoResponseBody Body;
        
        public GetHSRPAuthorizationnoResponse() {
        }
        
        public GetHSRPAuthorizationnoResponse(APCollectionWeb.TgS.GetHSRPAuthorizationnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHSRPAuthorizationnoResult;
        
        public GetHSRPAuthorizationnoResponseBody() {
        }
        
        public GetHSRPAuthorizationnoResponseBody(string GetHSRPAuthorizationnoResult) {
            this.GetHSRPAuthorizationnoResult = GetHSRPAuthorizationnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPChargesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPCharges", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateHSRPChargesRequestBody Body;
        
        public UpdateHSRPChargesRequest() {
        }
        
        public UpdateHSRPChargesRequest(APCollectionWeb.TgS.UpdateHSRPChargesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPChargesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CollectionDate;
        
        public UpdateHSRPChargesRequestBody() {
        }
        
        public UpdateHSRPChargesRequestBody(string Authno, decimal Amount, string CollectionDate) {
            this.Authno = Authno;
            this.Amount = Amount;
            this.CollectionDate = CollectionDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPChargesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPChargesResponse", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateHSRPChargesResponseBody Body;
        
        public UpdateHSRPChargesResponse() {
        }
        
        public UpdateHSRPChargesResponse(APCollectionWeb.TgS.UpdateHSRPChargesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPChargesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPChargesResult;
        
        public UpdateHSRPChargesResponseBody() {
        }
        
        public UpdateHSRPChargesResponseBody(string UpdateHSRPChargesResult) {
            this.UpdateHSRPChargesResult = UpdateHSRPChargesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPLaserCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPLaserCodes", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateHSRPLaserCodesRequestBody Body;
        
        public UpdateHSRPLaserCodesRequest() {
        }
        
        public UpdateHSRPLaserCodesRequest(APCollectionWeb.TgS.UpdateHSRPLaserCodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPLaserCodesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Frontlasercode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Rearlasercode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Embossingdate;
        
        public UpdateHSRPLaserCodesRequestBody() {
        }
        
        public UpdateHSRPLaserCodesRequestBody(string Authno, string Frontlasercode, string Rearlasercode, string Embossingdate) {
            this.Authno = Authno;
            this.Frontlasercode = Frontlasercode;
            this.Rearlasercode = Rearlasercode;
            this.Embossingdate = Embossingdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPLaserCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPLaserCodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateHSRPLaserCodesResponseBody Body;
        
        public UpdateHSRPLaserCodesResponse() {
        }
        
        public UpdateHSRPLaserCodesResponse(APCollectionWeb.TgS.UpdateHSRPLaserCodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPLaserCodesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPLaserCodesResult;
        
        public UpdateHSRPLaserCodesResponseBody() {
        }
        
        public UpdateHSRPLaserCodesResponseBody(string UpdateHSRPLaserCodesResult) {
            this.UpdateHSRPLaserCodesResult = UpdateHSRPLaserCodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAffixationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAffixation", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateHSRPAffixationRequestBody Body;
        
        public UpdateHSRPAffixationRequest() {
        }
        
        public UpdateHSRPAffixationRequest(APCollectionWeb.TgS.UpdateHSRPAffixationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAffixationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Affixationdate;
        
        public UpdateHSRPAffixationRequestBody() {
        }
        
        public UpdateHSRPAffixationRequestBody(string Authno, string Affixationdate) {
            this.Authno = Authno;
            this.Affixationdate = Affixationdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAffixationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAffixationResponse", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateHSRPAffixationResponseBody Body;
        
        public UpdateHSRPAffixationResponse() {
        }
        
        public UpdateHSRPAffixationResponse(APCollectionWeb.TgS.UpdateHSRPAffixationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAffixationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPAffixationResult;
        
        public UpdateHSRPAffixationResponseBody() {
        }
        
        public UpdateHSRPAffixationResponseBody(string UpdateHSRPAffixationResult) {
            this.UpdateHSRPAffixationResult = UpdateHSRPAffixationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAvailableAtOfficeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAvailableAtOffice", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeRequestBody Body;
        
        public UpdateHSRPAvailableAtOfficeRequest() {
        }
        
        public UpdateHSRPAvailableAtOfficeRequest(APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAvailableAtOfficeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PlateAvailableatOfficeDate;
        
        public UpdateHSRPAvailableAtOfficeRequestBody() {
        }
        
        public UpdateHSRPAvailableAtOfficeRequestBody(string Authno, string PlateAvailableatOfficeDate) {
            this.Authno = Authno;
            this.PlateAvailableatOfficeDate = PlateAvailableatOfficeDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAvailableAtOfficeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAvailableAtOfficeResponse", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeResponseBody Body;
        
        public UpdateHSRPAvailableAtOfficeResponse() {
        }
        
        public UpdateHSRPAvailableAtOfficeResponse(APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAvailableAtOfficeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPAvailableAtOfficeResult;
        
        public UpdateHSRPAvailableAtOfficeResponseBody() {
        }
        
        public UpdateHSRPAvailableAtOfficeResponseBody(string UpdateHSRPAvailableAtOfficeResult) {
            this.UpdateHSRPAvailableAtOfficeResult = UpdateHSRPAvailableAtOfficeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRegnOnAuthorizationDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRegnOnAuthorizationDate", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateRequestBody Body;
        
        public UpdateRegnOnAuthorizationDateRequest() {
        }
        
        public UpdateRegnOnAuthorizationDateRequest(APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRegnOnAuthorizationDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        public UpdateRegnOnAuthorizationDateRequestBody() {
        }
        
        public UpdateRegnOnAuthorizationDateRequestBody(string date) {
            this.date = date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRegnOnAuthorizationDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRegnOnAuthorizationDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateResponseBody Body;
        
        public UpdateRegnOnAuthorizationDateResponse() {
        }
        
        public UpdateRegnOnAuthorizationDateResponse(APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateRegnOnAuthorizationDateResponseBody {
        
        public UpdateRegnOnAuthorizationDateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorizationnotRegisteredRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorizationnotRegistered", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.GetAuthorizationnotRegisteredRequestBody Body;
        
        public GetAuthorizationnotRegisteredRequest() {
        }
        
        public GetAuthorizationnotRegisteredRequest(APCollectionWeb.TgS.GetAuthorizationnotRegisteredRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAuthorizationnotRegisteredRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string todate;
        
        public GetAuthorizationnotRegisteredRequestBody() {
        }
        
        public GetAuthorizationnotRegisteredRequestBody(string fromdate, string todate) {
            this.fromdate = fromdate;
            this.todate = todate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorizationnotRegisteredResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorizationnotRegisteredResponse", Namespace="http://tempuri.org/", Order=0)]
        public APCollectionWeb.TgS.GetAuthorizationnotRegisteredResponseBody Body;
        
        public GetAuthorizationnotRegisteredResponse() {
        }
        
        public GetAuthorizationnotRegisteredResponse(APCollectionWeb.TgS.GetAuthorizationnotRegisteredResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAuthorizationnotRegisteredResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAuthorizationnotRegisteredResult;
        
        public GetAuthorizationnotRegisteredResponseBody() {
        }
        
        public GetAuthorizationnotRegisteredResponseBody(string GetAuthorizationnotRegisteredResult) {
            this.GetAuthorizationnotRegisteredResult = GetAuthorizationnotRegisteredResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HSRPAuthorizationServiceSoapChannel : APCollectionWeb.TgS.HSRPAuthorizationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HSRPAuthorizationServiceSoapClient : System.ServiceModel.ClientBase<APCollectionWeb.TgS.HSRPAuthorizationServiceSoap>, APCollectionWeb.TgS.HSRPAuthorizationServiceSoap {
        
        public HSRPAuthorizationServiceSoapClient() {
        }
        
        public HSRPAuthorizationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HSRPAuthorizationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HSRPAuthorizationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HSRPAuthorizationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APCollectionWeb.TgS.GetHSRPAuthorizationDetailsResponse APCollectionWeb.TgS.HSRPAuthorizationServiceSoap.GetHSRPAuthorizationDetails(APCollectionWeb.TgS.GetHSRPAuthorizationDetailsRequest request) {
            return base.Channel.GetHSRPAuthorizationDetails(request);
        }
        
        public string GetHSRPAuthorizationDetails(string fromdate, string todate, string officecode) {
            APCollectionWeb.TgS.GetHSRPAuthorizationDetailsRequest inValue = new APCollectionWeb.TgS.GetHSRPAuthorizationDetailsRequest();
            inValue.Body = new APCollectionWeb.TgS.GetHSRPAuthorizationDetailsRequestBody();
            inValue.Body.fromdate = fromdate;
            inValue.Body.todate = todate;
            inValue.Body.officecode = officecode;
            APCollectionWeb.TgS.GetHSRPAuthorizationDetailsResponse retVal = ((APCollectionWeb.TgS.HSRPAuthorizationServiceSoap)(this)).GetHSRPAuthorizationDetails(inValue);
            return retVal.Body.GetHSRPAuthorizationDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APCollectionWeb.TgS.GetHSRPAuthorizationnoResponse APCollectionWeb.TgS.HSRPAuthorizationServiceSoap.GetHSRPAuthorizationno(APCollectionWeb.TgS.GetHSRPAuthorizationnoRequest request) {
            return base.Channel.GetHSRPAuthorizationno(request);
        }
        
        public string GetHSRPAuthorizationno(string Authno) {
            APCollectionWeb.TgS.GetHSRPAuthorizationnoRequest inValue = new APCollectionWeb.TgS.GetHSRPAuthorizationnoRequest();
            inValue.Body = new APCollectionWeb.TgS.GetHSRPAuthorizationnoRequestBody();
            inValue.Body.Authno = Authno;
            APCollectionWeb.TgS.GetHSRPAuthorizationnoResponse retVal = ((APCollectionWeb.TgS.HSRPAuthorizationServiceSoap)(this)).GetHSRPAuthorizationno(inValue);
            return retVal.Body.GetHSRPAuthorizationnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APCollectionWeb.TgS.UpdateHSRPChargesResponse APCollectionWeb.TgS.HSRPAuthorizationServiceSoap.UpdateHSRPCharges(APCollectionWeb.TgS.UpdateHSRPChargesRequest request) {
            return base.Channel.UpdateHSRPCharges(request);
        }
        
        public string UpdateHSRPCharges(string Authno, decimal Amount, string CollectionDate) {
            APCollectionWeb.TgS.UpdateHSRPChargesRequest inValue = new APCollectionWeb.TgS.UpdateHSRPChargesRequest();
            inValue.Body = new APCollectionWeb.TgS.UpdateHSRPChargesRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Amount = Amount;
            inValue.Body.CollectionDate = CollectionDate;
            APCollectionWeb.TgS.UpdateHSRPChargesResponse retVal = ((APCollectionWeb.TgS.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPCharges(inValue);
            return retVal.Body.UpdateHSRPChargesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APCollectionWeb.TgS.UpdateHSRPLaserCodesResponse APCollectionWeb.TgS.HSRPAuthorizationServiceSoap.UpdateHSRPLaserCodes(APCollectionWeb.TgS.UpdateHSRPLaserCodesRequest request) {
            return base.Channel.UpdateHSRPLaserCodes(request);
        }
        
        public string UpdateHSRPLaserCodes(string Authno, string Frontlasercode, string Rearlasercode, string Embossingdate) {
            APCollectionWeb.TgS.UpdateHSRPLaserCodesRequest inValue = new APCollectionWeb.TgS.UpdateHSRPLaserCodesRequest();
            inValue.Body = new APCollectionWeb.TgS.UpdateHSRPLaserCodesRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Frontlasercode = Frontlasercode;
            inValue.Body.Rearlasercode = Rearlasercode;
            inValue.Body.Embossingdate = Embossingdate;
            APCollectionWeb.TgS.UpdateHSRPLaserCodesResponse retVal = ((APCollectionWeb.TgS.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPLaserCodes(inValue);
            return retVal.Body.UpdateHSRPLaserCodesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APCollectionWeb.TgS.UpdateHSRPAffixationResponse APCollectionWeb.TgS.HSRPAuthorizationServiceSoap.UpdateHSRPAffixation(APCollectionWeb.TgS.UpdateHSRPAffixationRequest request) {
            return base.Channel.UpdateHSRPAffixation(request);
        }
        
        public string UpdateHSRPAffixation(string Authno, string Affixationdate) {
            APCollectionWeb.TgS.UpdateHSRPAffixationRequest inValue = new APCollectionWeb.TgS.UpdateHSRPAffixationRequest();
            inValue.Body = new APCollectionWeb.TgS.UpdateHSRPAffixationRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Affixationdate = Affixationdate;
            APCollectionWeb.TgS.UpdateHSRPAffixationResponse retVal = ((APCollectionWeb.TgS.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPAffixation(inValue);
            return retVal.Body.UpdateHSRPAffixationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeResponse APCollectionWeb.TgS.HSRPAuthorizationServiceSoap.UpdateHSRPAvailableAtOffice(APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeRequest request) {
            return base.Channel.UpdateHSRPAvailableAtOffice(request);
        }
        
        public string UpdateHSRPAvailableAtOffice(string Authno, string PlateAvailableatOfficeDate) {
            APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeRequest inValue = new APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeRequest();
            inValue.Body = new APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.PlateAvailableatOfficeDate = PlateAvailableatOfficeDate;
            APCollectionWeb.TgS.UpdateHSRPAvailableAtOfficeResponse retVal = ((APCollectionWeb.TgS.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPAvailableAtOffice(inValue);
            return retVal.Body.UpdateHSRPAvailableAtOfficeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateResponse APCollectionWeb.TgS.HSRPAuthorizationServiceSoap.UpdateRegnOnAuthorizationDate(APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateRequest request) {
            return base.Channel.UpdateRegnOnAuthorizationDate(request);
        }
        
        public void UpdateRegnOnAuthorizationDate(string date) {
            APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateRequest inValue = new APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateRequest();
            inValue.Body = new APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateRequestBody();
            inValue.Body.date = date;
            APCollectionWeb.TgS.UpdateRegnOnAuthorizationDateResponse retVal = ((APCollectionWeb.TgS.HSRPAuthorizationServiceSoap)(this)).UpdateRegnOnAuthorizationDate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APCollectionWeb.TgS.GetAuthorizationnotRegisteredResponse APCollectionWeb.TgS.HSRPAuthorizationServiceSoap.GetAuthorizationnotRegistered(APCollectionWeb.TgS.GetAuthorizationnotRegisteredRequest request) {
            return base.Channel.GetAuthorizationnotRegistered(request);
        }
        
        public string GetAuthorizationnotRegistered(string fromdate, string todate) {
            APCollectionWeb.TgS.GetAuthorizationnotRegisteredRequest inValue = new APCollectionWeb.TgS.GetAuthorizationnotRegisteredRequest();
            inValue.Body = new APCollectionWeb.TgS.GetAuthorizationnotRegisteredRequestBody();
            inValue.Body.fromdate = fromdate;
            inValue.Body.todate = todate;
            APCollectionWeb.TgS.GetAuthorizationnotRegisteredResponse retVal = ((APCollectionWeb.TgS.HSRPAuthorizationServiceSoap)(this)).GetAuthorizationnotRegistered(inValue);
            return retVal.Body.GetAuthorizationnotRegisteredResult;
        }
    }
}
