//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace APCollectionWeb.BankDepositRequestWS_HR {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BankDepositRequestWS_Binding", Namespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws")]
    public partial class BankDepositRequestWS_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BankDepositRequestWS_Service() {
            this.Url = global::APCollectionWeb.Properties.Settings.Default.APCollectionWeb_BankDepositRequestWS_HR_BankDepositRequestWS_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/bankdepositrequestws:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("BankDepositRequestWS")]
        public BankDepositRequestWS Read(int TransactionID) {
            object[] results = this.Invoke("Read", new object[] {
                        TransactionID});
            return ((BankDepositRequestWS)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(int TransactionID) {
            this.ReadAsync(TransactionID, null);
        }
        
        /// <remarks/>
        public void ReadAsync(int TransactionID, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        TransactionID}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/bankdepositrequestws:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("BankDepositRequestWS")]
        public BankDepositRequestWS ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((BankDepositRequestWS)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/bankdepositrequestws:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BankDepositRequestWS[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] BankDepositRequestWS_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((BankDepositRequestWS[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(BankDepositRequestWS_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(BankDepositRequestWS_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/bankdepositrequestws:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/bankdepositrequestws:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/bankdepositrequestws:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref BankDepositRequestWS BankDepositRequestWS) {
            object[] results = this.Invoke("Create", new object[] {
                        BankDepositRequestWS});
            BankDepositRequestWS = ((BankDepositRequestWS)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(BankDepositRequestWS BankDepositRequestWS) {
            this.CreateAsync(BankDepositRequestWS, null);
        }
        
        /// <remarks/>
        public void CreateAsync(BankDepositRequestWS BankDepositRequestWS, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        BankDepositRequestWS}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/bankdepositrequestws:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref BankDepositRequestWS[] BankDepositRequestWS_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        BankDepositRequestWS_List});
            BankDepositRequestWS_List = ((BankDepositRequestWS[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(BankDepositRequestWS[] BankDepositRequestWS_List) {
            this.CreateMultipleAsync(BankDepositRequestWS_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(BankDepositRequestWS[] BankDepositRequestWS_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        BankDepositRequestWS_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws")]
    public partial class BankDepositRequestWS {
        
        private string keyField;
        
        private int transactionIDField;
        
        private bool transactionIDFieldSpecified;
        
        private System.DateTime deposit_DateField;
        
        private bool deposit_DateFieldSpecified;
        
        private string nAV_Bank_Account_CodeField;
        
        private string bank_NameField;
        
        private string branch_NameField;
        
        private decimal deposit_AmountField;
        
        private bool deposit_AmountFieldSpecified;
        
        private string deposit_ByField;
        
        private string stateIDField;
        
        private string central_Warehouse_CodeField;
        
        private string embosssing_Center_CodeField;
        
        private string affixation_Center_CodeField;
        
        private string rTO_Collection_Center_CodeField;
        
        private string collection_Agent_CodeField;
        
        private string zone_CodeField;
        
        private string userIDField;
        
        private System.DateTime currentDateField;
        
        private bool currentDateFieldSpecified;
        
        private string bank_Slip_NoField;
        
        private string remarksField;
        
        private string accountNoField;
        
        private Transaction_Status transaction_StatusField;
        
        private bool transaction_StatusFieldSpecified;
        
        private string nAV_Bank_Receipt_NoField;
        
        private int bank_Ledger_Entry_NoField;
        
        private bool bank_Ledger_Entry_NoFieldSpecified;
        
        private bool is_not_ReconcileField;
        
        private bool is_not_ReconcileFieldSpecified;
        
        private decimal reconcile_AmountField;
        
        private bool reconcile_AmountFieldSpecified;
        
        private bool collection_Entry_PostedField;
        
        private bool collection_Entry_PostedFieldSpecified;
        
        private int collection_Entry_NoField;
        
        private bool collection_Entry_NoFieldSpecified;
        
        private string responsibility_CenterField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public int TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionIDSpecified {
            get {
                return this.transactionIDFieldSpecified;
            }
            set {
                this.transactionIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Deposit_Date {
            get {
                return this.deposit_DateField;
            }
            set {
                this.deposit_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Deposit_DateSpecified {
            get {
                return this.deposit_DateFieldSpecified;
            }
            set {
                this.deposit_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NAV_Bank_Account_Code {
            get {
                return this.nAV_Bank_Account_CodeField;
            }
            set {
                this.nAV_Bank_Account_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bank_Name {
            get {
                return this.bank_NameField;
            }
            set {
                this.bank_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Branch_Name {
            get {
                return this.branch_NameField;
            }
            set {
                this.branch_NameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Deposit_Amount {
            get {
                return this.deposit_AmountField;
            }
            set {
                this.deposit_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Deposit_AmountSpecified {
            get {
                return this.deposit_AmountFieldSpecified;
            }
            set {
                this.deposit_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Deposit_By {
            get {
                return this.deposit_ByField;
            }
            set {
                this.deposit_ByField = value;
            }
        }
        
        /// <remarks/>
        public string StateID {
            get {
                return this.stateIDField;
            }
            set {
                this.stateIDField = value;
            }
        }
        
        /// <remarks/>
        public string Central_Warehouse_Code {
            get {
                return this.central_Warehouse_CodeField;
            }
            set {
                this.central_Warehouse_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Embosssing_Center_Code {
            get {
                return this.embosssing_Center_CodeField;
            }
            set {
                this.embosssing_Center_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Affixation_Center_Code {
            get {
                return this.affixation_Center_CodeField;
            }
            set {
                this.affixation_Center_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string RTO_Collection_Center_Code {
            get {
                return this.rTO_Collection_Center_CodeField;
            }
            set {
                this.rTO_Collection_Center_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Collection_Agent_Code {
            get {
                return this.collection_Agent_CodeField;
            }
            set {
                this.collection_Agent_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Zone_Code {
            get {
                return this.zone_CodeField;
            }
            set {
                this.zone_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime CurrentDate {
            get {
                return this.currentDateField;
            }
            set {
                this.currentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrentDateSpecified {
            get {
                return this.currentDateFieldSpecified;
            }
            set {
                this.currentDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Bank_Slip_No {
            get {
                return this.bank_Slip_NoField;
            }
            set {
                this.bank_Slip_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
            }
        }
        
        /// <remarks/>
        public Transaction_Status Transaction_Status {
            get {
                return this.transaction_StatusField;
            }
            set {
                this.transaction_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Transaction_StatusSpecified {
            get {
                return this.transaction_StatusFieldSpecified;
            }
            set {
                this.transaction_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NAV_Bank_Receipt_No {
            get {
                return this.nAV_Bank_Receipt_NoField;
            }
            set {
                this.nAV_Bank_Receipt_NoField = value;
            }
        }
        
        /// <remarks/>
        public int Bank_Ledger_Entry_No {
            get {
                return this.bank_Ledger_Entry_NoField;
            }
            set {
                this.bank_Ledger_Entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bank_Ledger_Entry_NoSpecified {
            get {
                return this.bank_Ledger_Entry_NoFieldSpecified;
            }
            set {
                this.bank_Ledger_Entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Is_not_Reconcile {
            get {
                return this.is_not_ReconcileField;
            }
            set {
                this.is_not_ReconcileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Is_not_ReconcileSpecified {
            get {
                return this.is_not_ReconcileFieldSpecified;
            }
            set {
                this.is_not_ReconcileFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Reconcile_Amount {
            get {
                return this.reconcile_AmountField;
            }
            set {
                this.reconcile_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reconcile_AmountSpecified {
            get {
                return this.reconcile_AmountFieldSpecified;
            }
            set {
                this.reconcile_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Collection_Entry_Posted {
            get {
                return this.collection_Entry_PostedField;
            }
            set {
                this.collection_Entry_PostedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Collection_Entry_PostedSpecified {
            get {
                return this.collection_Entry_PostedFieldSpecified;
            }
            set {
                this.collection_Entry_PostedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Collection_Entry_No {
            get {
                return this.collection_Entry_NoField;
            }
            set {
                this.collection_Entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Collection_Entry_NoSpecified {
            get {
                return this.collection_Entry_NoFieldSpecified;
            }
            set {
                this.collection_Entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws")]
    public enum Transaction_Status {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Posted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws")]
    public partial class BankDepositRequestWS_Filter {
        
        private BankDepositRequestWS_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public BankDepositRequestWS_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/bankdepositrequestws")]
    public enum BankDepositRequestWS_Fields {
        
        /// <remarks/>
        TransactionID,
        
        /// <remarks/>
        Deposit_Date,
        
        /// <remarks/>
        NAV_Bank_Account_Code,
        
        /// <remarks/>
        Bank_Name,
        
        /// <remarks/>
        Branch_Name,
        
        /// <remarks/>
        Deposit_Amount,
        
        /// <remarks/>
        Deposit_By,
        
        /// <remarks/>
        StateID,
        
        /// <remarks/>
        Central_Warehouse_Code,
        
        /// <remarks/>
        Embosssing_Center_Code,
        
        /// <remarks/>
        Affixation_Center_Code,
        
        /// <remarks/>
        RTO_Collection_Center_Code,
        
        /// <remarks/>
        Collection_Agent_Code,
        
        /// <remarks/>
        Zone_Code,
        
        /// <remarks/>
        UserID,
        
        /// <remarks/>
        CurrentDate,
        
        /// <remarks/>
        Bank_Slip_No,
        
        /// <remarks/>
        Remarks,
        
        /// <remarks/>
        AccountNo,
        
        /// <remarks/>
        Transaction_Status,
        
        /// <remarks/>
        NAV_Bank_Receipt_No,
        
        /// <remarks/>
        Bank_Ledger_Entry_No,
        
        /// <remarks/>
        Is_not_Reconcile,
        
        /// <remarks/>
        Reconcile_Amount,
        
        /// <remarks/>
        Collection_Entry_Posted,
        
        /// <remarks/>
        Collection_Entry_No,
        
        /// <remarks/>
        Responsibility_Center,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BankDepositRequestWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BankDepositRequestWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BankDepositRequestWS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BankDepositRequestWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BankDepositRequestWS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BankDepositRequestWS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BankDepositRequestWS BankDepositRequestWS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BankDepositRequestWS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BankDepositRequestWS[] BankDepositRequestWS_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BankDepositRequestWS[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591