//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationKIt4._5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.HSRPAuthorizationServiceSoap")]
    public interface HSRPAuthorizationServiceSoap {
        
        // CODEGEN: Generating message contract since element name fromdate from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHSRPAuthorizationDetails", ReplyAction="*")]
        IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsResponse GetHSRPAuthorizationDetails(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHSRPAuthorizationDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsResponse> GetHSRPAuthorizationDetailsAsync(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHSRPAuthorizationno", ReplyAction="*")]
        IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoResponse GetHSRPAuthorizationno(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHSRPAuthorizationno", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoResponse> GetHSRPAuthorizationnoAsync(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPCharges", ReplyAction="*")]
        IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesResponse UpdateHSRPCharges(IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPCharges", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesResponse> UpdateHSRPChargesAsync(IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPLaserCodes", ReplyAction="*")]
        IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesResponse UpdateHSRPLaserCodes(IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPLaserCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesResponse> UpdateHSRPLaserCodesAsync(IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPAffixation", ReplyAction="*")]
        IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationResponse UpdateHSRPAffixation(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPAffixation", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationResponse> UpdateHSRPAffixationAsync(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequest request);
        
        // CODEGEN: Generating message contract since element name Authno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPAvailableAtOffice", ReplyAction="*")]
        IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeResponse UpdateHSRPAvailableAtOffice(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHSRPAvailableAtOffice", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeResponse> UpdateHSRPAvailableAtOfficeAsync(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationDetails", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequestBody Body;
        
        public GetHSRPAuthorizationDetailsRequest() {
        }
        
        public GetHSRPAuthorizationDetailsRequest(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fromdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string todate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string officecode;
        
        public GetHSRPAuthorizationDetailsRequestBody() {
        }
        
        public GetHSRPAuthorizationDetailsRequestBody(string fromdate, string todate, string officecode) {
            this.fromdate = fromdate;
            this.todate = todate;
            this.officecode = officecode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsResponseBody Body;
        
        public GetHSRPAuthorizationDetailsResponse() {
        }
        
        public GetHSRPAuthorizationDetailsResponse(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHSRPAuthorizationDetailsResult;
        
        public GetHSRPAuthorizationDetailsResponseBody() {
        }
        
        public GetHSRPAuthorizationDetailsResponseBody(string GetHSRPAuthorizationDetailsResult) {
            this.GetHSRPAuthorizationDetailsResult = GetHSRPAuthorizationDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationno", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequestBody Body;
        
        public GetHSRPAuthorizationnoRequest() {
        }
        
        public GetHSRPAuthorizationnoRequest(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        public GetHSRPAuthorizationnoRequestBody() {
        }
        
        public GetHSRPAuthorizationnoRequestBody(string Authno) {
            this.Authno = Authno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHSRPAuthorizationnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHSRPAuthorizationnoResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoResponseBody Body;
        
        public GetHSRPAuthorizationnoResponse() {
        }
        
        public GetHSRPAuthorizationnoResponse(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHSRPAuthorizationnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetHSRPAuthorizationnoResult;
        
        public GetHSRPAuthorizationnoResponseBody() {
        }
        
        public GetHSRPAuthorizationnoResponseBody(string GetHSRPAuthorizationnoResult) {
            this.GetHSRPAuthorizationnoResult = GetHSRPAuthorizationnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPChargesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPCharges", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequestBody Body;
        
        public UpdateHSRPChargesRequest() {
        }
        
        public UpdateHSRPChargesRequest(IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPChargesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CollectionDate;
        
        public UpdateHSRPChargesRequestBody() {
        }
        
        public UpdateHSRPChargesRequestBody(string Authno, decimal Amount, string CollectionDate) {
            this.Authno = Authno;
            this.Amount = Amount;
            this.CollectionDate = CollectionDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPChargesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPChargesResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesResponseBody Body;
        
        public UpdateHSRPChargesResponse() {
        }
        
        public UpdateHSRPChargesResponse(IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPChargesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPChargesResult;
        
        public UpdateHSRPChargesResponseBody() {
        }
        
        public UpdateHSRPChargesResponseBody(string UpdateHSRPChargesResult) {
            this.UpdateHSRPChargesResult = UpdateHSRPChargesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPLaserCodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPLaserCodes", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequestBody Body;
        
        public UpdateHSRPLaserCodesRequest() {
        }
        
        public UpdateHSRPLaserCodesRequest(IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPLaserCodesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Frontlasercode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Rearlasercode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Embossingdate;
        
        public UpdateHSRPLaserCodesRequestBody() {
        }
        
        public UpdateHSRPLaserCodesRequestBody(string Authno, string Frontlasercode, string Rearlasercode, string Embossingdate) {
            this.Authno = Authno;
            this.Frontlasercode = Frontlasercode;
            this.Rearlasercode = Rearlasercode;
            this.Embossingdate = Embossingdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPLaserCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPLaserCodesResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesResponseBody Body;
        
        public UpdateHSRPLaserCodesResponse() {
        }
        
        public UpdateHSRPLaserCodesResponse(IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPLaserCodesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPLaserCodesResult;
        
        public UpdateHSRPLaserCodesResponseBody() {
        }
        
        public UpdateHSRPLaserCodesResponseBody(string UpdateHSRPLaserCodesResult) {
            this.UpdateHSRPLaserCodesResult = UpdateHSRPLaserCodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAffixationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAffixation", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequestBody Body;
        
        public UpdateHSRPAffixationRequest() {
        }
        
        public UpdateHSRPAffixationRequest(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAffixationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Affixationdate;
        
        public UpdateHSRPAffixationRequestBody() {
        }
        
        public UpdateHSRPAffixationRequestBody(string Authno, string Affixationdate) {
            this.Authno = Authno;
            this.Affixationdate = Affixationdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAffixationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAffixationResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationResponseBody Body;
        
        public UpdateHSRPAffixationResponse() {
        }
        
        public UpdateHSRPAffixationResponse(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAffixationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPAffixationResult;
        
        public UpdateHSRPAffixationResponseBody() {
        }
        
        public UpdateHSRPAffixationResponseBody(string UpdateHSRPAffixationResult) {
            this.UpdateHSRPAffixationResult = UpdateHSRPAffixationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAvailableAtOfficeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAvailableAtOffice", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequestBody Body;
        
        public UpdateHSRPAvailableAtOfficeRequest() {
        }
        
        public UpdateHSRPAvailableAtOfficeRequest(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAvailableAtOfficeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PlateAvailableatOfficeDate;
        
        public UpdateHSRPAvailableAtOfficeRequestBody() {
        }
        
        public UpdateHSRPAvailableAtOfficeRequestBody(string Authno, string PlateAvailableatOfficeDate) {
            this.Authno = Authno;
            this.PlateAvailableatOfficeDate = PlateAvailableatOfficeDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHSRPAvailableAtOfficeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHSRPAvailableAtOfficeResponse", Namespace="http://tempuri.org/", Order=0)]
        public IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeResponseBody Body;
        
        public UpdateHSRPAvailableAtOfficeResponse() {
        }
        
        public UpdateHSRPAvailableAtOfficeResponse(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHSRPAvailableAtOfficeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateHSRPAvailableAtOfficeResult;
        
        public UpdateHSRPAvailableAtOfficeResponseBody() {
        }
        
        public UpdateHSRPAvailableAtOfficeResponseBody(string UpdateHSRPAvailableAtOfficeResult) {
            this.UpdateHSRPAvailableAtOfficeResult = UpdateHSRPAvailableAtOfficeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HSRPAuthorizationServiceSoapChannel : IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HSRPAuthorizationServiceSoapClient : System.ServiceModel.ClientBase<IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap>, IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap {
        
        public HSRPAuthorizationServiceSoapClient() {
        }
        
        public HSRPAuthorizationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HSRPAuthorizationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HSRPAuthorizationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HSRPAuthorizationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsResponse IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.GetHSRPAuthorizationDetails(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequest request) {
            return base.Channel.GetHSRPAuthorizationDetails(request);
        }
        
        public string GetHSRPAuthorizationDetails(string fromdate, string todate, string officecode) {
            IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequest inValue = new IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequestBody();
            inValue.Body.fromdate = fromdate;
            inValue.Body.todate = todate;
            inValue.Body.officecode = officecode;
            IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsResponse retVal = ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).GetHSRPAuthorizationDetails(inValue);
            return retVal.Body.GetHSRPAuthorizationDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsResponse> IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.GetHSRPAuthorizationDetailsAsync(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequest request) {
            return base.Channel.GetHSRPAuthorizationDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsResponse> GetHSRPAuthorizationDetailsAsync(string fromdate, string todate, string officecode) {
            IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequest inValue = new IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationDetailsRequestBody();
            inValue.Body.fromdate = fromdate;
            inValue.Body.todate = todate;
            inValue.Body.officecode = officecode;
            return ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).GetHSRPAuthorizationDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoResponse IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.GetHSRPAuthorizationno(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequest request) {
            return base.Channel.GetHSRPAuthorizationno(request);
        }
        
        public string GetHSRPAuthorizationno(string Authno) {
            IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequest inValue = new IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequestBody();
            inValue.Body.Authno = Authno;
            IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoResponse retVal = ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).GetHSRPAuthorizationno(inValue);
            return retVal.Body.GetHSRPAuthorizationnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoResponse> IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.GetHSRPAuthorizationnoAsync(IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequest request) {
            return base.Channel.GetHSRPAuthorizationnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoResponse> GetHSRPAuthorizationnoAsync(string Authno) {
            IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequest inValue = new IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.GetHSRPAuthorizationnoRequestBody();
            inValue.Body.Authno = Authno;
            return ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).GetHSRPAuthorizationnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesResponse IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.UpdateHSRPCharges(IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequest request) {
            return base.Channel.UpdateHSRPCharges(request);
        }
        
        public string UpdateHSRPCharges(string Authno, decimal Amount, string CollectionDate) {
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequest inValue = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Amount = Amount;
            inValue.Body.CollectionDate = CollectionDate;
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesResponse retVal = ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPCharges(inValue);
            return retVal.Body.UpdateHSRPChargesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesResponse> IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.UpdateHSRPChargesAsync(IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequest request) {
            return base.Channel.UpdateHSRPChargesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesResponse> UpdateHSRPChargesAsync(string Authno, decimal Amount, string CollectionDate) {
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequest inValue = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPChargesRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Amount = Amount;
            inValue.Body.CollectionDate = CollectionDate;
            return ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPChargesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesResponse IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.UpdateHSRPLaserCodes(IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequest request) {
            return base.Channel.UpdateHSRPLaserCodes(request);
        }
        
        public string UpdateHSRPLaserCodes(string Authno, string Frontlasercode, string Rearlasercode, string Embossingdate) {
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequest inValue = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Frontlasercode = Frontlasercode;
            inValue.Body.Rearlasercode = Rearlasercode;
            inValue.Body.Embossingdate = Embossingdate;
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesResponse retVal = ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPLaserCodes(inValue);
            return retVal.Body.UpdateHSRPLaserCodesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesResponse> IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.UpdateHSRPLaserCodesAsync(IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequest request) {
            return base.Channel.UpdateHSRPLaserCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesResponse> UpdateHSRPLaserCodesAsync(string Authno, string Frontlasercode, string Rearlasercode, string Embossingdate) {
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequest inValue = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPLaserCodesRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Frontlasercode = Frontlasercode;
            inValue.Body.Rearlasercode = Rearlasercode;
            inValue.Body.Embossingdate = Embossingdate;
            return ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPLaserCodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationResponse IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.UpdateHSRPAffixation(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequest request) {
            return base.Channel.UpdateHSRPAffixation(request);
        }
        
        public string UpdateHSRPAffixation(string Authno, string Affixationdate) {
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequest inValue = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Affixationdate = Affixationdate;
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationResponse retVal = ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPAffixation(inValue);
            return retVal.Body.UpdateHSRPAffixationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationResponse> IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.UpdateHSRPAffixationAsync(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequest request) {
            return base.Channel.UpdateHSRPAffixationAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationResponse> UpdateHSRPAffixationAsync(string Authno, string Affixationdate) {
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequest inValue = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPAffixationRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.Affixationdate = Affixationdate;
            return ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPAffixationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeResponse IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.UpdateHSRPAvailableAtOffice(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequest request) {
            return base.Channel.UpdateHSRPAvailableAtOffice(request);
        }
        
        public string UpdateHSRPAvailableAtOffice(string Authno, string PlateAvailableatOfficeDate) {
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequest inValue = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.PlateAvailableatOfficeDate = PlateAvailableatOfficeDate;
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeResponse retVal = ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPAvailableAtOffice(inValue);
            return retVal.Body.UpdateHSRPAvailableAtOfficeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeResponse> IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap.UpdateHSRPAvailableAtOfficeAsync(IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequest request) {
            return base.Channel.UpdateHSRPAvailableAtOfficeAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeResponse> UpdateHSRPAvailableAtOfficeAsync(string Authno, string PlateAvailableatOfficeDate) {
            IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequest inValue = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequest();
            inValue.Body = new IntegrationKIt4._5.ServiceReference1.UpdateHSRPAvailableAtOfficeRequestBody();
            inValue.Body.Authno = Authno;
            inValue.Body.PlateAvailableatOfficeDate = PlateAvailableatOfficeDate;
            return ((IntegrationKIt4._5.ServiceReference1.HSRPAuthorizationServiceSoap)(this)).UpdateHSRPAvailableAtOfficeAsync(inValue);
        }
    }
}
